$font = Monospace

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = smooth,0.25,1,0.5,1
    animation = fadeIn,1,4,smooth
    animation = fadeOut,1,4,smooth
    animation = inputFieldDots,1,2,smooth
}

background {
    monitor =
    path = /usr/share/wallpapers/ScarletTree/contents/images_dark/5120x2880.png

    blur_passes = 1
    blur_size = 8

    noise = 0.012
    contrast = 0.88
    brightness = 0.62

    vibrancy = 0.10
    vibrancy_darkness = 0.35
}


input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 2
    rounding = 16

    inner_color = rgba(1d1c2b99)

    outer_color = rgba(7568d8ee) rgba(7b93d8ee) 45deg
    check_color = rgba(7b93d8ee) rgba(a084dcff) 45deg
    fail_color = rgba(ca6b82ff)

    font_color = rgba(aeb4e6ff)

    font_family = $font

    fade_on_empty = false

    placeholder_text = 输入密码
    fail_text = 密码错误

    dots_spacing = 0.28
    dots_size = 0.28

    position = 0,-20
    halign = center
    valign = center
}
label {
    monitor =
    text = $TIME

    color = rgba(b3b0d9ff)

    font_size = 92
    font_family = $font

    position = 0,200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%Y %B %d, %A"

    color = rgba(b3b0d9ff)

    font_size = 22
    font_family = $font

    position = 0,100
    halign = center
    valign = center
}
