# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Hypridle
# Original config submitted by https://github.com/SherLock707


general {
    #lock_cmd = pidof hyprlock || hyprlock # runs hyprlock if it is not already running (this is always run when "loginctl lock-session" is called)
    #lock_cmd = pidof swaylock || swaylock -i ~/Pcitures/1.png # runs hyprlock if it is not already running (this is always run when "loginctl lock-session" is called)
    lock_cmd = noctalia msg session lock

    # unlock_cmd = killall hyprlock # kills hyprlock when unlocking (this is always run when "loginctl unlock-session" is called)
    before_sleep_cmd = loginctl lock-session    # ensures that the session is locked before going to sleep
    #after_sleep_cmd = sleep 30 && pidof hyprlock && systemctl suspend
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
}


listener {
    timeout = 110
    on-timeout = brightnessctl -s set 10         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r
}

listener {
    timeout = 180                                 # 2min
    on-timeout = loginctl lock-session  
}

listener {
    timeout = 300                                                                                  
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'                            # screen off when timeout has passed
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r          # screen on when activity is detected after timeout has fired.
}
