-- Generated by Noctalia

local primary = "rgb(7aa2f7)"
local surface = "rgb(1a1b26)"
local secondary = "rgb(bb9af7)"
local error = "rgb(f7768e)"

hl.config({
	general = {
		col = {
			active_border = primary,
			inactive_border = surface,
		},
	},

	group = {
		col = {
			border_active = secondary,
			border_inactive = surface,
			border_locked_active = error,
			border_locked_inactive = surface,
		},

		groupbar = {
			col = {
				active = secondary,
				inactive = surface,
				locked_active = error,
				locked_inactive = surface,
			},
		},
	},
})
