-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "0x0", scale = 1 })
hl.monitor({ output = "DP-1", mode = "2560x1440@119.836", position = "0x0", scale = 1.25, vrr = 2, bitdepth = 10 })
